name: GiveAll
version: 1.0
author: Eisphoenix
main: de.eisphoenix.giveall.GiveAll
commands:
  giveall:
    usage: /<command> <menge>
    permission: giveall.use
    description: Gibt jedem Spieler das Item aus deiner Hand